# Generated by Django 3.1.5 on 2021-01-23 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210123_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, through='recipes.Process', to='recipes.Ingredient'),
        ),
    ]
