# Generated by Django 3.1.5 on 2021-01-23 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20210123_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='recipes.Process', to='recipes.Ingredient'),
        ),
    ]
